/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployerDashboardRouteImport } from './routes/employer/dashboard'
import { Route as CandidateDashboardRouteImport } from './routes/candidate/dashboard'
import { Route as CandidateMatchesIndexRouteImport } from './routes/candidate/matches/index'
import { Route as EmployerRoleNewRouteImport } from './routes/employer/role/new'
import { Route as EmployerReengageReengageIdRouteImport } from './routes/employer/reengage/$reengageId'
import { Route as CandidateReengageReengageIdRouteImport } from './routes/candidate/reengage/$reengageId'
import { Route as CandidateProfileSetupRouteImport } from './routes/candidate/profile/setup'
import { Route as CandidateProfileCapabilityRouteImport } from './routes/candidate/profile/capability'
import { Route as CandidateMatchesMatchIdRouteImport } from './routes/candidate/matches/$matchId'
import { Route as EmployerRoleRoleIdPoolRouteImport } from './routes/employer/role/$roleId/pool'
import { Route as EmployerRoleRoleIdCapabilityMapRouteImport } from './routes/employer/role/$roleId/capability-map'
import { Route as EmployerRoleRoleIdPoolIndexRouteImport } from './routes/employer/role/$roleId/pool/index'
import { Route as EmployerRoleRoleIdPoolMatchIdRouteImport } from './routes/employer/role/$roleId/pool/$matchId'
import { Route as EmployerRoleRoleIdPoolMatchIdIndexRouteImport } from './routes/employer/role/$roleId/pool/$matchId/index'
import { Route as EmployerRoleRoleIdPoolMatchIdOutreachRouteImport } from './routes/employer/role/$roleId/pool/$matchId/outreach'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateMatchesIndexRoute = CandidateMatchesIndexRouteImport.update({
  id: '/candidate/matches/',
  path: '/candidate/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoleNewRoute = EmployerRoleNewRouteImport.update({
  id: '/employer/role/new',
  path: '/employer/role/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerReengageReengageIdRoute =
  EmployerReengageReengageIdRouteImport.update({
    id: '/employer/reengage/$reengageId',
    path: '/employer/reengage/$reengageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateReengageReengageIdRoute =
  CandidateReengageReengageIdRouteImport.update({
    id: '/candidate/reengage/$reengageId',
    path: '/candidate/reengage/$reengageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateProfileSetupRoute = CandidateProfileSetupRouteImport.update({
  id: '/candidate/profile/setup',
  path: '/candidate/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileCapabilityRoute =
  CandidateProfileCapabilityRouteImport.update({
    id: '/candidate/profile/capability',
    path: '/candidate/profile/capability',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateMatchesMatchIdRoute = CandidateMatchesMatchIdRouteImport.update({
  id: '/candidate/matches/$matchId',
  path: '/candidate/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoleRoleIdPoolRoute = EmployerRoleRoleIdPoolRouteImport.update({
  id: '/employer/role/$roleId/pool',
  path: '/employer/role/$roleId/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoleRoleIdCapabilityMapRoute =
  EmployerRoleRoleIdCapabilityMapRouteImport.update({
    id: '/employer/role/$roleId/capability-map',
    path: '/employer/role/$roleId/capability-map',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerRoleRoleIdPoolIndexRoute =
  EmployerRoleRoleIdPoolIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmployerRoleRoleIdPoolRoute,
  } as any)
const EmployerRoleRoleIdPoolMatchIdRoute =
  EmployerRoleRoleIdPoolMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => EmployerRoleRoleIdPoolRoute,
  } as any)
const EmployerRoleRoleIdPoolMatchIdIndexRoute =
  EmployerRoleRoleIdPoolMatchIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmployerRoleRoleIdPoolMatchIdRoute,
  } as any)
const EmployerRoleRoleIdPoolMatchIdOutreachRoute =
  EmployerRoleRoleIdPoolMatchIdOutreachRouteImport.update({
    id: '/outreach',
    path: '/outreach',
    getParentRoute: () => EmployerRoleRoleIdPoolMatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/candidate/matches/$matchId': typeof CandidateMatchesMatchIdRoute
  '/candidate/profile/capability': typeof CandidateProfileCapabilityRoute
  '/candidate/profile/setup': typeof CandidateProfileSetupRoute
  '/candidate/reengage/$reengageId': typeof CandidateReengageReengageIdRoute
  '/employer/reengage/$reengageId': typeof EmployerReengageReengageIdRoute
  '/employer/role/new': typeof EmployerRoleNewRoute
  '/candidate/matches/': typeof CandidateMatchesIndexRoute
  '/employer/role/$roleId/capability-map': typeof EmployerRoleRoleIdCapabilityMapRoute
  '/employer/role/$roleId/pool': typeof EmployerRoleRoleIdPoolRouteWithChildren
  '/employer/role/$roleId/pool/$matchId': typeof EmployerRoleRoleIdPoolMatchIdRouteWithChildren
  '/employer/role/$roleId/pool/': typeof EmployerRoleRoleIdPoolIndexRoute
  '/employer/role/$roleId/pool/$matchId/outreach': typeof EmployerRoleRoleIdPoolMatchIdOutreachRoute
  '/employer/role/$roleId/pool/$matchId/': typeof EmployerRoleRoleIdPoolMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/candidate/matches/$matchId': typeof CandidateMatchesMatchIdRoute
  '/candidate/profile/capability': typeof CandidateProfileCapabilityRoute
  '/candidate/profile/setup': typeof CandidateProfileSetupRoute
  '/candidate/reengage/$reengageId': typeof CandidateReengageReengageIdRoute
  '/employer/reengage/$reengageId': typeof EmployerReengageReengageIdRoute
  '/employer/role/new': typeof EmployerRoleNewRoute
  '/candidate/matches': typeof CandidateMatchesIndexRoute
  '/employer/role/$roleId/capability-map': typeof EmployerRoleRoleIdCapabilityMapRoute
  '/employer/role/$roleId/pool': typeof EmployerRoleRoleIdPoolIndexRoute
  '/employer/role/$roleId/pool/$matchId/outreach': typeof EmployerRoleRoleIdPoolMatchIdOutreachRoute
  '/employer/role/$roleId/pool/$matchId': typeof EmployerRoleRoleIdPoolMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/candidate/matches/$matchId': typeof CandidateMatchesMatchIdRoute
  '/candidate/profile/capability': typeof CandidateProfileCapabilityRoute
  '/candidate/profile/setup': typeof CandidateProfileSetupRoute
  '/candidate/reengage/$reengageId': typeof CandidateReengageReengageIdRoute
  '/employer/reengage/$reengageId': typeof EmployerReengageReengageIdRoute
  '/employer/role/new': typeof EmployerRoleNewRoute
  '/candidate/matches/': typeof CandidateMatchesIndexRoute
  '/employer/role/$roleId/capability-map': typeof EmployerRoleRoleIdCapabilityMapRoute
  '/employer/role/$roleId/pool': typeof EmployerRoleRoleIdPoolRouteWithChildren
  '/employer/role/$roleId/pool/$matchId': typeof EmployerRoleRoleIdPoolMatchIdRouteWithChildren
  '/employer/role/$roleId/pool/': typeof EmployerRoleRoleIdPoolIndexRoute
  '/employer/role/$roleId/pool/$matchId/outreach': typeof EmployerRoleRoleIdPoolMatchIdOutreachRoute
  '/employer/role/$roleId/pool/$matchId/': typeof EmployerRoleRoleIdPoolMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
    | '/candidate/matches/$matchId'
    | '/candidate/profile/capability'
    | '/candidate/profile/setup'
    | '/candidate/reengage/$reengageId'
    | '/employer/reengage/$reengageId'
    | '/employer/role/new'
    | '/candidate/matches/'
    | '/employer/role/$roleId/capability-map'
    | '/employer/role/$roleId/pool'
    | '/employer/role/$roleId/pool/$matchId'
    | '/employer/role/$roleId/pool/'
    | '/employer/role/$roleId/pool/$matchId/outreach'
    | '/employer/role/$roleId/pool/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
    | '/candidate/matches/$matchId'
    | '/candidate/profile/capability'
    | '/candidate/profile/setup'
    | '/candidate/reengage/$reengageId'
    | '/employer/reengage/$reengageId'
    | '/employer/role/new'
    | '/candidate/matches'
    | '/employer/role/$roleId/capability-map'
    | '/employer/role/$roleId/pool'
    | '/employer/role/$roleId/pool/$matchId/outreach'
    | '/employer/role/$roleId/pool/$matchId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
    | '/candidate/matches/$matchId'
    | '/candidate/profile/capability'
    | '/candidate/profile/setup'
    | '/candidate/reengage/$reengageId'
    | '/employer/reengage/$reengageId'
    | '/employer/role/new'
    | '/candidate/matches/'
    | '/employer/role/$roleId/capability-map'
    | '/employer/role/$roleId/pool'
    | '/employer/role/$roleId/pool/$matchId'
    | '/employer/role/$roleId/pool/'
    | '/employer/role/$roleId/pool/$matchId/outreach'
    | '/employer/role/$roleId/pool/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  CandidateMatchesMatchIdRoute: typeof CandidateMatchesMatchIdRoute
  CandidateProfileCapabilityRoute: typeof CandidateProfileCapabilityRoute
  CandidateProfileSetupRoute: typeof CandidateProfileSetupRoute
  CandidateReengageReengageIdRoute: typeof CandidateReengageReengageIdRoute
  EmployerReengageReengageIdRoute: typeof EmployerReengageReengageIdRoute
  EmployerRoleNewRoute: typeof EmployerRoleNewRoute
  CandidateMatchesIndexRoute: typeof CandidateMatchesIndexRoute
  EmployerRoleRoleIdCapabilityMapRoute: typeof EmployerRoleRoleIdCapabilityMapRoute
  EmployerRoleRoleIdPoolRoute: typeof EmployerRoleRoleIdPoolRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/matches/': {
      id: '/candidate/matches/'
      path: '/candidate/matches'
      fullPath: '/candidate/matches/'
      preLoaderRoute: typeof CandidateMatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/role/new': {
      id: '/employer/role/new'
      path: '/employer/role/new'
      fullPath: '/employer/role/new'
      preLoaderRoute: typeof EmployerRoleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/reengage/$reengageId': {
      id: '/employer/reengage/$reengageId'
      path: '/employer/reengage/$reengageId'
      fullPath: '/employer/reengage/$reengageId'
      preLoaderRoute: typeof EmployerReengageReengageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/reengage/$reengageId': {
      id: '/candidate/reengage/$reengageId'
      path: '/candidate/reengage/$reengageId'
      fullPath: '/candidate/reengage/$reengageId'
      preLoaderRoute: typeof CandidateReengageReengageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile/setup': {
      id: '/candidate/profile/setup'
      path: '/candidate/profile/setup'
      fullPath: '/candidate/profile/setup'
      preLoaderRoute: typeof CandidateProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile/capability': {
      id: '/candidate/profile/capability'
      path: '/candidate/profile/capability'
      fullPath: '/candidate/profile/capability'
      preLoaderRoute: typeof CandidateProfileCapabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/matches/$matchId': {
      id: '/candidate/matches/$matchId'
      path: '/candidate/matches/$matchId'
      fullPath: '/candidate/matches/$matchId'
      preLoaderRoute: typeof CandidateMatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/role/$roleId/pool': {
      id: '/employer/role/$roleId/pool'
      path: '/employer/role/$roleId/pool'
      fullPath: '/employer/role/$roleId/pool'
      preLoaderRoute: typeof EmployerRoleRoleIdPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/role/$roleId/capability-map': {
      id: '/employer/role/$roleId/capability-map'
      path: '/employer/role/$roleId/capability-map'
      fullPath: '/employer/role/$roleId/capability-map'
      preLoaderRoute: typeof EmployerRoleRoleIdCapabilityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/role/$roleId/pool/': {
      id: '/employer/role/$roleId/pool/'
      path: '/'
      fullPath: '/employer/role/$roleId/pool/'
      preLoaderRoute: typeof EmployerRoleRoleIdPoolIndexRouteImport
      parentRoute: typeof EmployerRoleRoleIdPoolRoute
    }
    '/employer/role/$roleId/pool/$matchId': {
      id: '/employer/role/$roleId/pool/$matchId'
      path: '/$matchId'
      fullPath: '/employer/role/$roleId/pool/$matchId'
      preLoaderRoute: typeof EmployerRoleRoleIdPoolMatchIdRouteImport
      parentRoute: typeof EmployerRoleRoleIdPoolRoute
    }
    '/employer/role/$roleId/pool/$matchId/': {
      id: '/employer/role/$roleId/pool/$matchId/'
      path: '/'
      fullPath: '/employer/role/$roleId/pool/$matchId/'
      preLoaderRoute: typeof EmployerRoleRoleIdPoolMatchIdIndexRouteImport
      parentRoute: typeof EmployerRoleRoleIdPoolMatchIdRoute
    }
    '/employer/role/$roleId/pool/$matchId/outreach': {
      id: '/employer/role/$roleId/pool/$matchId/outreach'
      path: '/outreach'
      fullPath: '/employer/role/$roleId/pool/$matchId/outreach'
      preLoaderRoute: typeof EmployerRoleRoleIdPoolMatchIdOutreachRouteImport
      parentRoute: typeof EmployerRoleRoleIdPoolMatchIdRoute
    }
  }
}

interface EmployerRoleRoleIdPoolMatchIdRouteChildren {
  EmployerRoleRoleIdPoolMatchIdOutreachRoute: typeof EmployerRoleRoleIdPoolMatchIdOutreachRoute
  EmployerRoleRoleIdPoolMatchIdIndexRoute: typeof EmployerRoleRoleIdPoolMatchIdIndexRoute
}

const EmployerRoleRoleIdPoolMatchIdRouteChildren: EmployerRoleRoleIdPoolMatchIdRouteChildren =
  {
    EmployerRoleRoleIdPoolMatchIdOutreachRoute:
      EmployerRoleRoleIdPoolMatchIdOutreachRoute,
    EmployerRoleRoleIdPoolMatchIdIndexRoute:
      EmployerRoleRoleIdPoolMatchIdIndexRoute,
  }

const EmployerRoleRoleIdPoolMatchIdRouteWithChildren =
  EmployerRoleRoleIdPoolMatchIdRoute._addFileChildren(
    EmployerRoleRoleIdPoolMatchIdRouteChildren,
  )

interface EmployerRoleRoleIdPoolRouteChildren {
  EmployerRoleRoleIdPoolMatchIdRoute: typeof EmployerRoleRoleIdPoolMatchIdRouteWithChildren
  EmployerRoleRoleIdPoolIndexRoute: typeof EmployerRoleRoleIdPoolIndexRoute
}

const EmployerRoleRoleIdPoolRouteChildren: EmployerRoleRoleIdPoolRouteChildren =
  {
    EmployerRoleRoleIdPoolMatchIdRoute:
      EmployerRoleRoleIdPoolMatchIdRouteWithChildren,
    EmployerRoleRoleIdPoolIndexRoute: EmployerRoleRoleIdPoolIndexRoute,
  }

const EmployerRoleRoleIdPoolRouteWithChildren =
  EmployerRoleRoleIdPoolRoute._addFileChildren(
    EmployerRoleRoleIdPoolRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  CandidateMatchesMatchIdRoute: CandidateMatchesMatchIdRoute,
  CandidateProfileCapabilityRoute: CandidateProfileCapabilityRoute,
  CandidateProfileSetupRoute: CandidateProfileSetupRoute,
  CandidateReengageReengageIdRoute: CandidateReengageReengageIdRoute,
  EmployerReengageReengageIdRoute: EmployerReengageReengageIdRoute,
  EmployerRoleNewRoute: EmployerRoleNewRoute,
  CandidateMatchesIndexRoute: CandidateMatchesIndexRoute,
  EmployerRoleRoleIdCapabilityMapRoute: EmployerRoleRoleIdCapabilityMapRoute,
  EmployerRoleRoleIdPoolRoute: EmployerRoleRoleIdPoolRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
