/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployerDashboardRouteImport } from './routes/employer/dashboard'
import { Route as CandidateDashboardRouteImport } from './routes/candidate/dashboard'
import { Route as EmployerRoleNewRouteImport } from './routes/employer/role/new'
import { Route as EmployerRoleRoleIdPoolRouteImport } from './routes/employer/role/$roleId/pool'
import { Route as EmployerRoleRoleIdCapabilityMapRouteImport } from './routes/employer/role/$roleId/capability-map'
import { Route as EmployerRoleRoleIdPoolMatchIdRouteImport } from './routes/employer/role/$roleId/pool/$matchId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoleNewRoute = EmployerRoleNewRouteImport.update({
  id: '/employer/role/new',
  path: '/employer/role/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoleRoleIdPoolRoute = EmployerRoleRoleIdPoolRouteImport.update({
  id: '/employer/role/$roleId/pool',
  path: '/employer/role/$roleId/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoleRoleIdCapabilityMapRoute =
  EmployerRoleRoleIdCapabilityMapRouteImport.update({
    id: '/employer/role/$roleId/capability-map',
    path: '/employer/role/$roleId/capability-map',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerRoleRoleIdPoolMatchIdRoute =
  EmployerRoleRoleIdPoolMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => EmployerRoleRoleIdPoolRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/role/new': typeof EmployerRoleNewRoute
  '/employer/role/$roleId/capability-map': typeof EmployerRoleRoleIdCapabilityMapRoute
  '/employer/role/$roleId/pool': typeof EmployerRoleRoleIdPoolRouteWithChildren
  '/employer/role/$roleId/pool/$matchId': typeof EmployerRoleRoleIdPoolMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/role/new': typeof EmployerRoleNewRoute
  '/employer/role/$roleId/capability-map': typeof EmployerRoleRoleIdCapabilityMapRoute
  '/employer/role/$roleId/pool': typeof EmployerRoleRoleIdPoolRouteWithChildren
  '/employer/role/$roleId/pool/$matchId': typeof EmployerRoleRoleIdPoolMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/role/new': typeof EmployerRoleNewRoute
  '/employer/role/$roleId/capability-map': typeof EmployerRoleRoleIdCapabilityMapRoute
  '/employer/role/$roleId/pool': typeof EmployerRoleRoleIdPoolRouteWithChildren
  '/employer/role/$roleId/pool/$matchId': typeof EmployerRoleRoleIdPoolMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
    | '/employer/role/new'
    | '/employer/role/$roleId/capability-map'
    | '/employer/role/$roleId/pool'
    | '/employer/role/$roleId/pool/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
    | '/employer/role/new'
    | '/employer/role/$roleId/capability-map'
    | '/employer/role/$roleId/pool'
    | '/employer/role/$roleId/pool/$matchId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
    | '/employer/role/new'
    | '/employer/role/$roleId/capability-map'
    | '/employer/role/$roleId/pool'
    | '/employer/role/$roleId/pool/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerRoleNewRoute: typeof EmployerRoleNewRoute
  EmployerRoleRoleIdCapabilityMapRoute: typeof EmployerRoleRoleIdCapabilityMapRoute
  EmployerRoleRoleIdPoolRoute: typeof EmployerRoleRoleIdPoolRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/role/new': {
      id: '/employer/role/new'
      path: '/employer/role/new'
      fullPath: '/employer/role/new'
      preLoaderRoute: typeof EmployerRoleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/role/$roleId/pool': {
      id: '/employer/role/$roleId/pool'
      path: '/employer/role/$roleId/pool'
      fullPath: '/employer/role/$roleId/pool'
      preLoaderRoute: typeof EmployerRoleRoleIdPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/role/$roleId/capability-map': {
      id: '/employer/role/$roleId/capability-map'
      path: '/employer/role/$roleId/capability-map'
      fullPath: '/employer/role/$roleId/capability-map'
      preLoaderRoute: typeof EmployerRoleRoleIdCapabilityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/role/$roleId/pool/$matchId': {
      id: '/employer/role/$roleId/pool/$matchId'
      path: '/$matchId'
      fullPath: '/employer/role/$roleId/pool/$matchId'
      preLoaderRoute: typeof EmployerRoleRoleIdPoolMatchIdRouteImport
      parentRoute: typeof EmployerRoleRoleIdPoolRoute
    }
  }
}

interface EmployerRoleRoleIdPoolRouteChildren {
  EmployerRoleRoleIdPoolMatchIdRoute: typeof EmployerRoleRoleIdPoolMatchIdRoute
}

const EmployerRoleRoleIdPoolRouteChildren: EmployerRoleRoleIdPoolRouteChildren =
  {
    EmployerRoleRoleIdPoolMatchIdRoute: EmployerRoleRoleIdPoolMatchIdRoute,
  }

const EmployerRoleRoleIdPoolRouteWithChildren =
  EmployerRoleRoleIdPoolRoute._addFileChildren(
    EmployerRoleRoleIdPoolRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerRoleNewRoute: EmployerRoleNewRoute,
  EmployerRoleRoleIdCapabilityMapRoute: EmployerRoleRoleIdCapabilityMapRoute,
  EmployerRoleRoleIdPoolRoute: EmployerRoleRoleIdPoolRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
