/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployerDashboardRouteImport } from './routes/employer/dashboard'
import { Route as CandidateDashboardRouteImport } from './routes/candidate/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/candidate/dashboard'
    | '/employer/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
